version: '3.8'

services:
  app1:
    image: arandhawa98/app-nodejs
    ports:
      - 8081:8080
    networks:
      - mynetwork
    container_name: myappcontainer1

  app2:
    image: arandhawa98/app-nodejs
    ports:
      - 8082:8080
    networks:
      - mynetwork
    container_name: myappcontainer2

networks:
  mynetwork:
    driver: bridge
